### ISSUE TITLE
Hashlink doesn't render without moving or resizing window

### ISSUE THREAD

**Issue by xiaoshuangLi** [HaxeFoundation/hashlink#200] opened 2018-10-27 11:40 UTC
Hi, i tried to use hashlink to render the sample on mac. But it doesn't render anything if i don't resize or move the window. Just like the following GIF. And it happend to every sample i found, like heaps samples. 

heaps 1.5.0
Haxe Compiler 4.0.0-preview.5+7eb789f
HL/JIT 1.8.0
HashLink Debugger 0.4.4
VSCode 1.28.2 x64
macOS Mojave

**compile.hxml**
```
-lib heaps
-lib hlsdl
-hl Main.hl
-main Main
-D windowSize=1366x768
-debug
```

![ezgif-2-bdddb80354c5](https://user-images.githubusercontent.com/12060054/47603481-f5a67100-da1e-11e8-8871-b69cf9563dec.gif)

**Comment by ncannasse** [comment] 2018-10-27 12:29
Could you add a trace in  heaps/h3d/Engine.onWindowResize (line 250):
`trace(window.width,window.height,driver.isDisposed())`
and the same in "resize" function (line 270)
That will help understand what's going on.
Thanks

**Comment by xiaoshuangLi** [comment] 2018-10-27 15:10
Sorry, i think maybe you misunderstand what i'm trying to say. The sample i programed is very sample, i do nothing when the window resize. I think is a bug for hashlink on mac.

And sorry to bother you about that. I'll try to debugger to find where go wrong. Thanks for you time.

**Main.hx**
```haxe
class Main extends hxd.App {
  var bmp : h2d.Bitmap;
  override function init() {
    var tile = h2d.Tile.fromColor(0xFF0000, 100, 100);

    bmp = new h2d.Bitmap(tile, s2d);

    bmp.x = s2d.width * 0.5;
    bmp.y = s2d.height * 0.5;
    bmp.alpha = 0.5;

    bmp.tile.dx = Std.int(bmp.tile.width * -0.5);
    bmp.tile.dy = Std.int(bmp.tile.height * -0.5);
  }

  override function update(dt: Float) {
    bmp.rotation += 0.1;
  }

  static function main() {
    new Main();
  }
}

```

**Comment by xiaoshuangLi** [comment] 2018-10-28 03:08
@ncannasse Finally, i removed the code from **heaps/h3d/Engine**.It still happened.When i debugger it on chrome, i found out there are no next move for **heaps** if the remove the code.By the way, the sample worked perfectly on chrome.

**heaps/h3d/Engine.onWindowResize**
```haxe
function onWindowResize() {
  // if( autoResize && !driver.isDisposed() ) {
  //  var w = window.width, h = window.height;
  //  if( w != width || h != height )
  //    resize(w, h);
  //  onResized();
  // }
}
```

**Comment by xiaoshuangLi** [comment] 2018-10-28 03:08
@ncannasse Finally, i removed the code from **heaps/h3d/Engine**.It still happened.When i debugger it on chrome, i found out there are no next move for **heaps** if the remove the code.By the way, the sample worked perfectly on chrome.

**heaps/h3d/Engine.onWindowResize**
```haxe
function onWindowResize() {
  // if( autoResize && !driver.isDisposed() ) {
  //  var w = window.width, h = window.height;
  //  if( w != width || h != height )
  //    resize(w, h);
  //  onResized();
  // }
}
```

**Comment by ncannasse** [comment] 2018-10-30 09:38
@xiaoshuangLi yes I understood correctly what you meant, that's why I ask you if you could add a trace and send me the output so I can confirm what's happening.

From what you said, it seems `onWindowResize` is never called, does adding `onWindowResize()` at the end of hxd/Engine.hx `function new()` (line 81) fix the issue?

**Comment by shakesoda** [comment] 2018-10-30 12:55
this is a bug in Mojave. it's been causing headaches for anything that uses OpenGL... looks like there's a fix/workaround in SDL2 HG, though.

**Comment by ncannasse** [comment] 2018-10-31 09:49
@shakesoda any pointers ?

**Comment by shakesoda** [comment] 2018-10-31 10:22
@ncannasse maybe this workaround is viable w/o SDL update? https://discourse.libsdl.org/t/macos-10-14-mojave-issues/25060/2

otherwise, looks like it should work against latest SDL2. here's (hopefully all?) the relevant info:
bug https://bugzilla.libsdl.org/show_bug.cgi?id=4272
fix 1 https://hg.libsdl.org/SDL/rev/55489adbb75
fix 2 https://hg.libsdl.org/SDL/rev/86dcfbbcacaf

**Comment by shakesoda** [comment] 2018-11-01 03:33
update: SDL 2.0.9 was just released. updating framework should take care of everything here, with any luck

**Comment by ncannasse** [comment] 2018-12-02 17:12
Closing as it's related to SDL and will be fixed in next SDL release.

**Closed by ncannasse** 2018-12-02 17:12 UTC
