### ISSUE TITLE
Linux Mint "make install" issue with libhl.so being installed into "/usr/local/" and not being seen by HashLink

### ISSUE THREAD

**Issue by Ateknia** [HaxeFoundation/hashlink#386] opened 2020-05-26 17:24 UTC
> hl: error while loading shared libraries: libhl.so: cannot open shared object file: No such file or directory

On Linux Mint 19.3 Cinnamon 64bit, HashLink 1.11
Issue: `make install` installs `libhl.so` into `/usr/local/lib` and HashLink doesn't see it.
Workaround: use `make INSTALL_DIR=/usr install` instead as suggested in [#221 ](https://github.com/HaxeFoundation/hashlink/issues/221#issuecomment-455892192)

**Comment by Aurel300** [comment] 2020-05-26 17:45
Can you share your `LD_LIBRARY_PATH`? I am guessing Nicolas/the Makefile assumes `/usr/local/lib` is always in that path, but maybe it is not the case on some distributions.

**Comment by Aboideau** [comment] 2020-05-27 05:45
`echo $LD_LIBRARY_PATH` returns an empty new line.

**Comment by Aurel300** [comment] 2020-05-27 08:44
Can you also try `sudo ldconfig -v` to make it verbose? As a workaround that doesn't change the install location, you can run HashLink with `LD_LIBRARY_PATH` set manually, e.g. `LD_LIBRARY_PATH=/usr/local/lib hl foobar.hl`.

**Comment by Aboideau** [comment] 2020-05-27 09:41
I believe I did everything exactly the same as yesterday to reproduce this issue but the error changed. I ran `sudo make INSTALL_DIR=/usr uninstall` to remove and then `sudo make install`.

`src/module.c(352) : FATAL ERROR : Failed to load library ssl.hdll` when running HashLink 1.11. All of the `.hdll` files are present in `/usr/local/lib`. `LD_LIBRARY_PATH` remains empty.

`sudo ldconfig -v` shows `libhl.so`, [full `sudo ldconfig -v` output](https://pastebin.com/i3jAkhMk).

Setting `LD_LIBRARY_PATH` before HashLink does work as a workaround if you wish to keep everything in `/usr/local/lib`.

Is it possible that it's an issue with Mint? Mint has installed new updates just a few hours ago, and I seem to be unable to reproduce the exact issue I had yesterday on two separate PCs running the same version of Mint. Or I might just be reading too much into it.

**Comment by Aurel300** [comment] 2020-05-27 10:40
Ok, looking through how [`dlopen`](https://linux.die.net/man/3/dlopen) operates (which is what loads HDLL files in HashLink), I can see how this might happen. If there is nothing in `LD_LIBRARY_PATH`, `dlopen` consults `/etc/ld.so.cache` (generated by `ldconfig`). I assume `sudo ldconfig -v` shows `libhl.so` but not the `.hdll` files? Does the cache file list them?

It may be that `ldconfig` on your distribution performs the search for libraries differently, and completely ignores the non-standard `.hdll` libraries. I wouldn't say this is an issue with Mint as it is really uncommon to install `so` files as anything other than `.so`.

**Comment by Aboideau** [comment] 2020-05-27 11:46
`sudo ldconfig -v` and `ldconfig -p` only have `.so` files listed while `.hdll` aren't present.

Is there any reason why `.hdll` libraries can't be in the `.so` format? Or maybe included in the `hl` program itself? I don't know much about native compilation nor Linux, sorry if I'm asking something stupid.

**Comment by Aurel300** [comment] 2020-05-27 13:19
I suppose you can put an adjustment to your `LD_LIBRARY_PATH` in your shell profile or something …

The `hdll`/`so` thing is something for @ncannasse to answer. HDLLs are "HashLink dynamic libraries" and on Linux they are in fact just `so` (shared object) files with a different file extension. This seems to continue the tradition from Neko's NDLLs which worked pretty much the same. I guess some advantages are that the loader does not need to load libraries differently on different OS, and that the filename is consistent across platforms?

**Comment by ConstNW** [comment] 2020-06-23 13:14
Stuck with the same problem on fresh Ubuntu 20.04 LTS (Focal Fossa) and temporarily fix it with `LD_LIBRARY_PATH=/usr/local/lib`

**Comment by JuDelCo** [comment] 2020-07-18 13:15
Same problem with PopOS 20.04 (Ubuntu based)

I manage to install it uninstalling it first and then installing it again. I don't know why. This are all the commands I run:

```
sudo make install       # It installs in /usr/local/ ...

echo $LD_LIBRARY_PATH   # This returns an empty line.
sudo ldconfig -v        # Here it shows like /usr/local/ is being used for libhl.so but hl still doesn't work.

sudo make uninstall
sudo make install       # NOW works !
```

**Comment by saem** [comment] 2020-07-23 08:01
@ncannasse I'm testing it locally, I'll create a PR if you'd like that should fix this and https://github.com/HaxeFoundation/hashlink/issues/221.

## CMake Fix
I believe the fix for this and the various dynamic linking is documented here: https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#common-questions

Specifically, I was able to add: `set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)` before the `install(...)` directive on line 321 in CMakeLists.txt -- haven't tested it just yet. But this should "do the right thing", though I don't believe it's as flexible as what I came up with for make. I haven't touched native development in easily over a decade so I'm basically a total newbie. This might needs a guard for platforms -- but CMake might be smart enough to figure that out.

## Make Fix
For the make file, updating LFLAGS on Linux on line 92 to:
`LFLAGS += -lm -Wl,-rpath,.:'$ORIGIN/../lib':$(PREFIX)/lib -Wl,--export-dynamic -Wl,--no-undefined` seems to work. That should search for the shared objects in the following order:
1. immediate directory, required for build/test while developing hl or overriding the so for an install
2. offset off the executable, allowing for relocatable executables
3. based on the prefix what should end up getting used for most installs

Note that all this will be ignored if for some reason any sort of elevate privileges are involved (setuid) but that's a security matter and systems get awful strict about library paths. Excellent reference on rpaths, etc... https://amir.rachum.com/blog/2016/09/17/shared-libraries/

cc: @mchudleigh

**Comment by YRTV** [comment] 2020-07-31 17:03
There is two different issues here.
1. Install command on debian and derivatives is `sudo make install` binaries in /usr/local/bin which does not belong to **root** will run in Secure-execution mode.
```
Secure-execution mode
       For security reasons, if the dynamic linker determines  that  a  binary
       should be run in secure-execution mode, the effects of some environment
       variables are voided or modified,  and  furthermore  those  environment
       variables  are  stripped from the environment, so that the program does
       not even see the definitions.  Some of these environment variables  af‐
       fect  the operation of the dynamic linker itself, and are described be‐
       low.   Other  environment  variables  treated  in  this  way   include:
       GCONV_PATH,   GETCONF_DIR,   HOSTALIASES,  LOCALDOMAIN,  LOCPATH,  MAL‐
       LOC_TRACE, NIS_PATH, NLSPATH,  RESOLV_HOST_CONF,  RES_OPTIONS,  TMPDIR,
       and TZDIR.
```
2. Loading .hdlls on demand at runtime fails on ubuntu and down the distro tree. I suspect apparmor. It works on arch.

**Comment by YRTV** [comment] 2020-07-31 17:28
It's not AppArmor. `sudo aa-teardown` did not help with `src/module.c(352) : FATAL ERROR : Failed to load library` on ubuntu 20.04

**Comment by YRTV** [comment] 2020-07-31 20:47
I broke hdll runtime loading on arch by using  `/etc/ld.so.conf.d/libc.conf` instead of  `$LD_LIBRARY_PATH`. libhl.so still load hdlls give `src/module.c(352) : FATAL ERROR : Failed to load library` error. Can't find any documentation about reasons of this.

**Comment by YRTV** [comment] 2020-08-01 09:17
hdlls are named incorrectly. dlopen() looks  for *64.hdll names (sdl64.hdll, openall64.hdll) fails and some fallback search routine kicks in ingnoring `etc/ld.so.conf`

**Closed** 2022-04-26 08:22 UTC
