### ISSUE TITLE
JIT support I64

### ISSUE THREAD

**Issue by ConstNW** [HaxeFoundation/hashlink#283] opened 2019-08-16 11:21 UTC
on Winfows jit throw exception on operations with I64 types
```haxe
package;

class Main
{
    public static function main( ) : Void
    {
        var ts_start : hl.I64 = 1;
        trace(ts_start);
    }
}
```
```
JIT ERROR 0 (jit.c line 3073)
```
In other cases got errors:
```
JIT ERROR 4 (jit.c line 1856)
```
and
```
JIT ERROR 0 (jit.c line 3036)
```

**Comment by ncannasse** [comment] 2019-08-16 12:16
Duplicate of #180

**Closed by ncannasse** 2019-08-16 12:16 UTC
