### ISSUE TITLE
Sys.stdout().write turning LF to CRLF on windows

### ISSUE THREAD

**Issue by JeremyGiner** [HaxeFoundation/hashlink#300] opened 2019-09-07 14:45 UTC
I have the following code : 
```
var o = Bytes.ofString( "\n" );
Sys.stdout().write(  o );
```
When i launch it on windows with `hl Test.hl > test_result`,  the resulting file contains CRLF instead of just LF. 

I'm not sure if the problem comes from windows cmd or HL althought i try using cygwin and got the same result.

It's pretty annoying since i'm trying to print CRLF which is then turn into CRCRLF.

Version : hl-1.10.0-win

**Comment by Aurel300** [comment] 2019-09-07 17:52
Duplicate of https://github.com/HaxeFoundation/haxe/issues/8379

**Closed** 2019-09-09 19:13 UTC
